### ISSUE TITLE
Agriculture Layout

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/workshoplocator#18]
Seems that the layout of Agricultural workshops could and should be improved

```
Input Workshop Mix
Enter number of each workshop type in order
Agriculture Biotech Electronics Energy HeavyIndustry
2 0 0 0 0

Layout
Agriculture Chambers (Workshop): location: 5 3 temp: 40 !!!!  productivity: 52
        Greenhouse (Module): location: 4 3
        Greenhouse (Module): location: 6 3
        Solar Cells (Module): location: 5 4
        Artificial-G Lab (Module): location: 5 2
Agriculture Chambers (Workshop): location: 7 3 temp: 40 !!!!  productivity: 42
        Artificial-G Lab (Module): location: 5 2
        Greenhouse (Module): location: 8 3
        Solar Cells (Module): location: 7 4
        Artificial-G Lab (Module): location: 7 2
```

**Comment by JamesBremner** [comment]
Adding a third, shared greenhouse gets the productivity up to 73

**Comment by ztlawton** [comment]
Are you hard-coding a fixed layout for all the different Workshop types? Or can the code adapt the layouts for more efficient placements?

The Energy Workshop layout seems pretty constrained, as moving any Modules farther away from the Workshop results in less-than-maximum productivity unless additional Modules are added to compensate. But the Agriculture Workshop should be more flexible, because it doesn't need all the Modules to be as close as possible to achieve maximum productivity.

**Comment by JamesBremner** [comment]
`Are you hard-coding a fixed layout for all the different Workshop types?`

Yes.  

The only input you specified was the workshop mix - the number of workshops of each kind.  If you want the user to move modules around then you should have specified that.

**Comment by ztlawton** [comment]
I don't really want the _user_ to move Modules around. I want the _code_ to move Modules around to find the arrangement that uses the fewest Modules and Links to satisfy all Workshop requirements.
